deploy:
  stage: deploy
  image: alpine
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - chmod 400 mmakara.pem
    - ssh-add mmakara.pem
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - scp -o StrictHostKeyChecking=no docker-compose.yml ec2-user@3.71.114.74:/home/ec2-user
    - ssh -o StrictHostKeyChecking=no ec2-user@3.71.114.74 "docker-compose pull ; docker-compose up --force-recreate -d ; docker image prune -f"
